import turtle
screen = turtle.Screen()
pen = turtle.Turtle()

screen.setup(width = 450 , height = 380)

screen.bgcolor("light blue")
screen.title("Bhart_flag")
pen.penup()
pen.goto(-150,125)
pen.pendown()
pen.color("black")
pen.fillcolor("orange")
pen.begin_fill()
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.end_fill()

pen.fillcolor("white")
pen.begin_fill()
pen.right(90)
pen.forward(70)
pen.left(90)
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.end_fill()

pen.fillcolor("green")
pen.begin_fill()
pen.right(90)
pen.forward(70)
pen.left(90)
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.forward(300)
pen.right(90)
pen.forward(70)
pen.right(90)
pen.end_fill()
pen.end_fill()

pen.fillcolor("blue")
pen.begin_fill()
pen.penup()
pen.goto(0,-5)
pen.pendown()
pen.circle(25)
pen.end_fill()

pen.fillcolor("white")
pen.begin_fill()
pen.penup()
pen.goto(0,-3)
pen.pendown()
pen.circle(23)
pen.end_fill()

pen.color("blue")
pen.width(2)
a = 0
while(a<24):
    a = a + 1
    pen.right(270)
    pen.forward(23)
    pen.right(180)
    pen.forward(23)
    pen.left(90)
    pen.circle(23,15)
pen.width(1)

turtle.done()
screen.exitonclick()